server.port=8080

# ============================
# Database (default: local H2)
# ============================
#spring.datasource.url=jdbc:h2:file:./data/calendar-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:oracle:thin:@//192.168.64.30:1521/lin
spring.datasource.username=ATUL_VERMA_LinDB
spring.datasource.password=VATGYurlkJHDfJk
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# Hibernate/JPA configuration for Oracle
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.generate_statistics=false

# Oracle-specific connection pool settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# To run against another RDBMS, override via env/system props:
# spring.datasource.url=...
# spring.datasource.username=...
# spring.datasource.password=...
# spring.jpa.properties.hibernate.dialect=...

#========== Google OAuth Configuration ==========
oauth.google.client-id=808325637026-ed3cg3rp954cn6lnch186242noq728qf.apps.googleusercontent.com
oauth.google.client-secret=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
oauth.google.redirect-uri=https://kebab-recast-shrill.ngrok-free.dev/api/oauth/callback/google

# ========== Outlook OAuth Configuration ==========
oauth.outlook.client-id=e10025d3-6ca2-4c1c-bd31-509933da96df
oauth.outlook.client-secret=1Uz8Q~1JMES33obTqBXzH~Sqxg1vSErq70xwKbH0
oauth.outlook.redirect-uri=https://kebab-recast-shrill.ngrok-free.dev/api/oauth/callback/outlook
#oauth.outlook.redirect-uri=http://localhost:8080/api/oauth/callback/outlook
#outlook.auth.url=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#outlook.token.url=https://login.microsoftonline.com/common/oauth2/v2.0/token
#outlook.scope=offline_access Calendars.ReadWrite User.Read

# ============================
# Logging
# ============================
# ============================
# Webhook
# ============================
webhook.callback.base-url=https://kebab-recast-shrill.ngrok-free.dev

# ============================
# Logging
# ============================
logging.level.root=INFO
logging.level.com.omvrti.calendar_service=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
