server.port=8090

# ============================
# Database (default: local H2)
# ============================
#spring.datasource.url=jdbc:h2:file:./data/calendar-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:oracle:thin:@//192.168.64.30:1521/lin
spring.datasource.username=ATUL_VERMA_LinDB
spring.datasource.password=VATGYurlkJHDfJk
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# To run against another RDBMS, override via env/system props:
# spring.datasource.url=...
# spring.datasource.username=...
# spring.datasource.password=...
# spring.jpa.properties.hibernate.dialect=...

#========== Google OAuth Configuration ==========
oauth.google.client-id=808325637026-d2f0huddmiu5oubm7qdjkns4pjpceu17.apps.googleusercontent.com
oauth.google.client-secret=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
oauth.google.redirect-uri=http://localhost:8090/api/oauth/callback/google

# ========== Outlook OAuth Configuration ==========
oauth.outlook.client-id=e10025d3-6ca2-4c1c-bd31-509933da96df
oauth.outlook.client-secret=1Uz8Q~1JMES33obTqBXzH~Sqxg1vSErq70xwKbH0
oauth.outlook.redirect-uri=http://localhost:8090/api/oauth/callback/outlook

# ============================
# Logging
# ============================
logging.level.root=INFO
logging.level.com.omvrti.calendar_service=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
