ALTER TABLE CUSTOMER_USER_SYNC ADD (SOURCE_SYSTEM VARCHAR2(50), LAST_SYNC_TOKEN VARCHAR2(2000), VERSION NUMBER(19,0) DEFAULT 0 NOT NULL);
ALTER TABLE CU_SYNC_CALENDAR ADD (SOURCE_SYSTEM VARCHAR2(50), VERSION NUMBER(19,0) DEFAULT 0 NOT NULL);
ALTER TABLE CU_SYNC_CALENDAR_WEBHOOK ADD (IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL, DELETED_ON DATE);
ALTER TABLE CU_SYNC_CALENDAR_EVENT ADD (IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, SOURCE_SYSTEM VARCHAR2(50), VERSION NUMBER(19,0) DEFAULT 0 NOT NULL);
ALTER TABLE CU_SYNC_CALENDAR_EVENT_GUEST ADD (IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL, IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL, DELETED_ON DATE);

ALTER TABLE CUSTOMER_USER_SYNC ADD CONSTRAINT CUSTOMER_USER_SYNC_UK1 UNIQUE (CUSTOMER_USER_ID, SYNC_VENDOR_ID, SYNC_ACCOUNT_REFERENCE);
ALTER TABLE CU_SYNC_CALENDAR ADD CONSTRAINT CU_SYNC_CALENDAR_UK1 UNIQUE (CUSTOMER_USER_SYNC_ID, CALENDAR_REFERENCE);
ALTER TABLE CU_SYNC_CALENDAR_EVENT ADD CONSTRAINT CU_SYNC_CALENDAR_EVENT_UK1 UNIQUE (CU_SYNC_CALENDAR_ID, CALENDAR_EVENT_REFERENCE);
ALTER TABLE CU_SYNC_CALENDAR_EVENT_GUEST ADD CONSTRAINT CU_SYNC_CAL_EVENT_GUEST_UK1 UNIQUE (CU_SYNC_CAL_EVENT_ID, GUEST_EMAIL);

UPDATE CU_SYNC_CALENDAR_WEBHOOK SET IS_ACTIVE = 0, IS_DELETED = 1, DELETED_ON = SYSDATE WHERE EXPIRY_DATE < SYSDATE;
UPDATE CU_SYNC_CALENDAR_EVENT SET IS_ACTIVE = 0, IS_DELETED = 1, DELETED_ON = SYSDATE WHERE IS_DELETED = 1;
UPDATE CU_SYNC_CALENDAR_EVENT_GUEST SET IS_ACTIVE = 0, IS_DELETED = 1, DELETED_ON = SYSDATE WHERE IS_DELETED = 1;
